# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: prompterday-CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v3    
      
    - name: Setup node.js
      uses: actions/setup-node@v3.8.1
      with:
        node-version: 18.x
        cache: 'npm'
        
    - name: Install Backend-Server
      run: npm ci

    - name: Compile Backend-Server
      run: npm run build
      
    #"node_modules/*" "coverage/*" "src/*" "test/*" "README.md" "*.git*" 파일 제외 후 레퍼지토 압축
    - name: Make a zip file
      run: zip -r ./$GITHUB_SHA.zip . -x "node_modules/*" "coverage/*" "src/*" "test/*" "README.md" "*.git*"
      shell: bash

    #S3 자격 증명 수행
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # zip파일 S3업로드
    - name: Upload to S3
      run: aws s3 cp --region ${{ secrets.AWS_REGION }} ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

env:
  S3_BUCKET_NAME: kimsoo-bucket # S3 버킷 이름
  PROJECT_NAME: server-file # S3 버킷 내 폴더 이름 임의로 지정 가능
  AWS_CODEDEPLOY_APPLICATION_NAME: connection-deploy # CodeDeploy 애플리케이션 이름입니다.
  AWS_CODEDEPLOY_DEPLOYMENT_GROUP_NAME: connection-deploy-dev-group # CodeDeploy 배포 그룹 이름입니다.
      
